### PR TITLE
add new sample for AWS EC2 SSM

### PR DESCRIPTION
**Pull request by chrisgala**
Adding sample for dynamic inventory through https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html

### CODE REVIEW

**Comment by dmagnis-epignosis** [comment]
LGTM

**Comment by lemonmojo** [comment]
Unfortunately the export file is corrupt (see screenshot below).
Please fix those issues, then we can merge.

Screenshot 2023-07-24 at 11 50 28

**Comment by chrisgala** [comment]
> Unfortunately the export file is corrupt (see screenshot below). Please fix those issues, then we can merge.
> Screenshot 2023-07-24 at 11 50 28

It should be fixed now.

**Comment by lemonmojo** [comment]
@chrisgala thx, merged!

**Pull request merged**
