### PR TITLE
Powershell ad servers advanced dynamic folder

### PR DESCRIPTION
**Pull request by armentpau**
I added my script I have been working on in the Active Directory folder.  I wasn't sure if you wanted me to add it in another folder or add it to the current Active Directory folder.  How would you like to structure that?

There are configuration notes in the rdfe file and does not require anyone to modify any of the code to update the settings in the script.

This is built on top of the simplified AD script I wrote earlier but retracted due to it requiring users to modify the code - and it was pointed out that as little code adjustments should be done as possible.

Paul

### CODE REVIEW

**Comment by patschi** [comment]
Some thoughts from me:
1. The Configurator title has a lower-case "Royal Ts", instead uppercase ("Royal TS")
2. Wouldn't the field name "PDC" fit better than just "DC"?
3. Regarding "Credential Name": In my opinion it might be easier to rely on the set Credentials of the Dynamic Folder-object within Royal TS. If you use "Use credentials from parent folder" for generated objects by your PowerShell script, it's going to use defined credentials from the Dynamic Folder. This way the user can 1) set the credentials in a familiar way, 2) use a specific credential, a credential name and also specify credentials directly. (For objects `"CredentialsFromParent": true`, for folders see more details on [RoyalJSON docs page 10](https://www.royalapplications.com/go/rjson-documentation))

Further little things:
4. I've never really used "Get-ADComputer" and stuff and was a bit confused what "SearchScope" actually does. I've failed to get the simplified AD Script running because I was using "Base" instead of "Subtree". MIght it possible to add a short sentence next to the select box to explain further what the selected option does?
5. When no domain name is specified, the "..."-button for the "OU selector" just doesn't do anything. Of course I see the point why, but maybe there could be a warning popup saying "Please enter domain first" or something like that.

Very amazing work! Working fine in my lab!

**Comment by lemonmojo** [comment]
@armentpau In addition to @patschi's comments, could you please add a version number and author information to the notes field so that users of your script can easily identify if they're running the latest version?

thx,
felix

**Comment by armentpau** [comment]
Thanks for the feedback - I'll take a look and then upload the updated version.

**Comment by armentpau** [comment]
I added/fixed the following things:

Added ability to use either named or inherited credentials (if field is left blank then inherited credentials are used - this is explained in the tooltip)

Added author notes and version information

Changed label from DC to PDC

Updated Royal Ts label to Royal TS

Added hover tips to all the fields - including SearchScope.  Mousing over the options will provide a popup information dialog that will last 30 seconds.

Disabled the OU selection button if the PDC field is blank due to no domain being entered

**Comment by patschi** [comment]
Thanks a lot Paul! Truly an amazing work!

I've ran some more tests on your updated version and I've probably come across two issues (sorry for being so annoying! :)):
* I'm not able to get the hover tips for said fields, including SearchScope. Nothing dealbreaker IMHO, but I'm curious if that's a general issue, or just on my machine?
* Always when reloading the Dynamic Folder I'm getting the Configuration UI, even everything is configured. Is this intended?

And it might worth thinking about: You might want to use "$ID$" replacement token to create an unique configuration file for each Dynamic Folder - without requiring the user to set an unique `ConfigFileName` within CustomProperties. (so using `$ID$.xml`, instead of hardcoded `settings.xml` file)

As already mentioned, great work Paul! And a happy new year! :)

**Comment by armentpau** [comment]
Weird on the popup not coming up.  I did make sure to include the information in the notes section - on all of my test machines I am seeing the popup.  I have a few other things in mind as well (rich text box) but won't get time to work no that until sometime next week.

Yes the dialog should show up every time.  If no interaction is made over the windows in five seconds it closes and takes the settings that were previously there.  I made it that way so every time I refresh I can select a different OU (you would not believe how many times I have to change what servers I work with each time - its almost always different). 

Thanks for the idea on using the ID.  I'll do a little thinking/tinkering if I can get it to work with my workflow.  That's how this thing came about - I needed something to work with the workflow I use at work with Royal.

**Comment by lemonmojo** [comment]
@armentpau We merged your PR now. If you have some additional changes/fixes ready, please submit a new PR. Many thx for your contribution!!

**Pull request merged**
