### PR TITLE
Adds Dynamic Folder Scripts for AD and System Center Virtual Machine Manager

### PR DESCRIPTION
**Pull request by janegilring**
Adds Get-ServerFromAD.ps1 and Get-ServerFromSCVMM.ps1, which will retrieve data from Active Directory and System Center Virtual Machine Manager.

### CODE REVIEW

**Comment by StefanKoell** [comment]
Hi Jan,
thanks for your PR.  It would be great if you can provide the .rdfe files (including scripts, description and parameterization using custom properties) instead of just the scripts. Check out the readme for more information here: https://github.com/royalapplications/toolbox/blob/master/Dynamic%20Folder/README.md

You may also check out the other .rdfe files to see how they are put together.

If you have any questions, ket me know.

Thanks!

**Comment by lemonmojo** [comment]
@janegilring: Any news on this PR?

**Comment by janegilring** [comment]
I'm sorry for the late response. The rdfe-files is now added.
I also included one I created for Azure as well.

**Comment by lemonmojo** [comment]
@janegilring: Thx for the update!

Can you please remove the ps1 files if they contain the same content as the scripts in the rdfe files? If they contain different or additional stuff, please add readme files which explain their usage.

Additionally, can you please split this into to PRs so that we can review and approve them individually?

Thx,
Felix

**Comment by janegilring** [comment]
Sure, I removed the ps1-files and will re-add the Azure rdfe in a separate PR when this one is merged.

**Pull request merged**
