### PR TITLE
API v5, Python 3 only, Omit Domain field

### PR DESCRIPTION
**Pull request by deworn**
[new] added custom field "Omit Domain" because no such options is in RoyalTS Credentials for Dynamic Folders
[change] Pleasant Password Server API changed from v4 to v5
[change] moved to Python 3 only
[fix] fixed print statements for errors

### CODE REVIEW

**Comment by lemonmojo** [comment]
Hi @deworn,

first of all: Thx a lot for your contribution!

Before we merge this, there are a couple changes we'd like to see:
- Please ensure that your Dynamic Folder export contains notes just like the existing Pleasant Password script in this repository. These help users get started with the dynamic folder and ensure they know the prerequisites and about the various configuration fields.
- If possible, please ensure your script works with Python 2 as well as Python 3. Python 2 is still very popular and is the version that ships out of the box with macOS.
- Are the V4 and V5 APIs compatible? Or in other words: Does this only work with either version or both? In any case, please include this info in the notes section too.

thx,
felix

**Comment by deworn** [comment]
Hi felix,

as for:
notes) Yeah, I've missed this, sorry. Will add it.

python version) I had some problems with current approach - print statement is different in v2 vs v3 and there were errors about errors because of this in our environment. So I've decided to drop Python2 support for this. If you want, I can create new file for Python 2 but I think they should be separated.

API version) Version 4 and 5 are somewhat compatible but Pleasant Server have v5 for some time now. Not sure when they'll drop v4 completely so I wanted to update it.

I understand 1 file for all would be nice but in this case it all points to 4 files - python versions and API versions combinations.
I can create them all, is this ok?

Cheers,
Deworn

**Comment by lemonmojo** [comment]
Hey @deworn,

- Regarding Python 2 vs. 3:
I think the only stumbling block here is how printing to stderr is done and this can be rewritten in a Python 2 and 3 compatible way. For instance, like this:
```
from __future__ import print_function
import sys
from functools import partial

printError = partial(print, file=sys.stderr)

printError("test")
```

The tkinter import would then also have to be reverted to the previous version:
```
try:
    # for Python2
    from Tkinter import * 
except ImportError:
    # for Python3
    from tkinter import *
```

- Regarding Pleasant Password API Version:
It seems like the only change required in the script is the API endpoint URL: `/api/v4/rest/credentialgroup`  vs. `/api/v5/rest/folders`.
If that is indeed correct I think it would make sense to support both APIs in the script by letting the user pass a configuration value to request a specific version.
I'd suggest implement this using a Yes/No custom property ("Use deprecated V4 API") which is set to No by default.

What do you think?

cheers,
felix

**Comment by deworn** [comment]
Hi felix,

Thanks for the suggestions.

You were right, I've done the changes and it now works with Python 2 and 3 (once again) and you can also select APIv4 or APIv5 (defaults to APIv5). Notes also updated.

Cheers,
deworn

**Comment by lemonmojo** [comment]
@deworn LGTM!

One last change request before I merge this:
- Can you please prefix the token strings (`"$CustomProperty.ServerURL$"`, `"$EffectiveUsername$"`, etc.) with `r` so that we don't run into issues when the values contain escape characters (like a backslash).
So `"$EffectiveUsername$"` becomes `r"$EffectiveUsername$"`

thx,
felix

**Comment by deworn** [comment]
Hi felix,

Done.
I've also added some error handling for server connections.

cheers,
deworn

**Comment by lemonmojo** [comment]
@deworn Just merged. Thx a lot for your contribution!

**Pull request merged**
