### PR TITLE
Updated the 1Password dynamic folder to support multiple vaults and biometrics

### PR DESCRIPTION
**Pull request by jvwam**
Based on [this gist](https://gist.github.com/joachimtingvold/fef17f2772ebd623b1b1ea4135e1e7f5) which adds biometric support
Found in [issue #60](https://github.com/royalapplications/toolbox/issues/60)
This update allows multiple vaults, just add them in the vault field as a comma separated list
This is also .rdfx rather than the existing .rdfe

This is my first pull request ever so let me know if you need more info or anything

### CODE REVIEW

**Comment by lemonmojo** [comment]
@jvwam I've taken a quick look at this. Unfortunately there are a couple of issues:
* The description and notes are completely missing (please take a look at the [current version of the sample](https://github.com/royalapplications/toolbox/blob/master/Dynamic%20Folder/1Password/1Password%20(Python).rdfe))
* There's no error handling if the "OP Path" custom properties are not configured so the error message in this case is not very specific
* The same thing applies to the account and vault properties. Since these are optional and only used for filtering, you might want to remove the "TODO" values from the script export manually.
* Even after signing in using the `op` command in Terminal, I'm not able to make the script work. It always shows `You are not currently signed in. Please run `op signin --help` for instructions` even though running `op item list` from the terminal works.

**Comment by joachimtingvold** [comment]
These should be fixed (and some other things) in PR #71. Sorry for "hijacking" your PR, @jvwam (-:

**Comment by WarrenAndMahoneyICT** [comment]
> 

No worries at all! Thanks for updating mine and adding even more, it's much appreciated :) 
I've been trying to find a few minutes to make the changes and now I don't have to haha. 
I'm not sure if it's relevant or where to mention it, but anyone on Windows should be using version 2.19.0 of op.exe as that fixes the bug where you had to unlock 1Password first (or open it if it was already unlocked)

**Comment by jvwam** [comment]
@joachimtingvold 
No worries at all! Thanks for updating mine and adding even more, it's much appreciated :)
I've been trying to find a few minutes to make the changes and now I don't have to haha.
I'm not sure if it's relevant or where to mention it, but anyone on Windows should be using version 2.19.0 of op.exe as that fixes the bug where you had to unlock 1Password first (or open it if it was already unlocked)

**Comment by lemonmojo** [comment]
I'm closing this in favor of https://github.com/royalapplications/toolbox/pull/71.

**Pull request closed without merging**
