### PR TITLE
Dynamic Folders: Added Hetzner Cloud

### PR DESCRIPTION
**Pull request by mxschmitt**
Hi there,

in this Pull  Request, I'm adding Dynamic Folder support for the cloud hosting provider Hetzner:
[https://hetzner.de/cloud](https://hetzner.de/cloud)

I've added documentation in the Notes section like the other existing dynamic folder scripts.

Best regards

Max

### CODE REVIEW

**Comment by lemonmojo** [comment]
Thx for the contribution!

Just one change request: Could you please use a protected custom property instead of custom field 11? Custom Properties can be named per instance and thus provide a better user experience.

**Comment by lemonmojo** [comment]
@mxschmitt Yes, it is! But since custom properties are much more flexible and allow individual fields to be named we're preferring those over custom fields.

**Comment by lemonmojo** [comment]
@mxschmitt Thx for making the change as requested. Please also update the documentation in the notes section to reference the custom property instead of the custom field.

**Comment by mxschmitt** [comment]
Oh, very good point, sorry ;)

**Comment by lemonmojo** [comment]
Thx, merged!

**Pull request merged**
