### PR TITLE
Create Foreman (PHP).rdfe

### PR DESCRIPTION
**Pull request by QDaniel**
Dynamic Folder by Foreman API

### CODE REVIEW

**Comment by lemonmojo** [comment]
@QDaniel Thx for your contribution!

A couple of requests before we're able to merge this:
- Please ensure that your Dynamic Folder includes a short description which describes what it does
- Please add a more complete description, including requirements and setup instructions in the "Notes" section

Please have a look at our other samples as all of them include a description and notes which allow users of the script to get started quickly.

**Comment by QDaniel** [comment]
I have add  Setup Notes and better Error Information as Todos

**Comment by lemonmojo** [comment]
@QDaniel Thx for the update! The description (on the main property page of the dynamic folder) is still missing. This is used in the dynamic folder gallery to show the user a quick summary of what the dynamic folder does. Additionally, you're referencing a custom property from the notes and your script which isn't included in the dynamic folder export. And one more thing: The "Foreman URL" value is empty in the custom properties section. Please ensure you select "Anonymize Custom Properties" when exporting the dynamic folder to have any values replaced with "TODO" after importing the dynamic folder.

**Comment by lemonmojo** [comment]
@QDaniel Also, it would be better to let Royal TS/X handle any errors. Everything that's written to stderr will be displayed by Royal TS/X when refreshing the dynamic folder.

**Comment by QDaniel** [comment]
Which setting did you meen? I have two settings. Both are Exported.

**Comment by lemonmojo** [comment]
@QDaniel Not sure what went wrong but I see both settings now. Merged now! Thx again for your contribution!

**Pull request merged**
