### PR TITLE
Support for the new LAPS (April 2023 Update)

### PR DESCRIPTION
**Pull request by krikk**
modified the existing LAPS Dynamic folder to work with the "new" LAPS (April 2023 Update),  This Version fetches the Connections out from AD (Get-ADComputer) and the LAPS user and Password also via AD (Get-LapsADPassword)

also solved the problem with german umlauts, added description field from AD

### CODE REVIEW

**Comment by lemonmojo** [comment]
@krikk This adds a completely new file to the repo `new LAPS (Windows PowerShell).rdfx` instead of replacing the original.
Is this new script not compatible with older versions of LAPS or did this happen accidentally?

**Comment by krikk** [comment]
the "new" LAPS (released April 2023) has new powershell Commands, which are different to the "old" one, so this script will only work with "new" LAPS and not with the old one, so it's better to offer both, ...the old one for people still using the old laps, and the "new" version for up-to-date Systems

**Comment by lemonmojo** [comment]
@krikk Thx for the clarification. So, should we maybe name the new script `LAPS April 2023 (Windows PowerShell).rdfx` instead of `new LAPS (Windows PowerShell).rdfx` to make that more clear?

**Comment by krikk** [comment]
as the "new" LAPS is inbuild into the OS with the April 2023 OS Updates, it will become the new standard very fast

so i would suggest the following:
rename the old "LAPS (Windows PowerShell).rdfe" to "LAPS (deprecated) (Windows PowerShell).rdfe" <- this because the the old LAPS need additional software and non-standard powershell Modules
and the new file (mine) to "LAPS April 2023 (Windows PowerShell).rdfe"

**Comment by lemonmojo** [comment]
@krikk Yeah, that sounds good to me!

**Comment by krikk** [comment]
nearly forgot this one, renamed like planned, i think it ready to merge

**Comment by alexhass** [comment]
Why not naming the old laps LEGACY or classic?

**Pull request merged**
